const initialProducts = [
  {id:'p1',name:'Menulis yang Menjual',category:'E-book',price:35000,description:'Panduan praktis merangkai kata yang jelas, hangat, dan meyakinkan.',color:'#efb879',download:'https://example.com/download/menulis'},
  {id:'p2',name:'Kelas Canva untuk Pemula',category:'Modul',price:49000,description:'Modul langkah demi langkah membuat desain yang rapi dan siap pakai.',color:'#b8d7ba',download:'https://example.com/download/canva'},
  {id:'p3',name:'Notion Life Planner',category:'Template',price:29000,description:'Atur proyek, rutinitas, dan impian Anda dalam satu dashboard.',color:'#cabce7',download:'https://example.com/download/notion'},
  {id:'p4',name:'Suara untuk Fokus',category:'Audio',price:15000,description:'Koleksi ambience tenang untuk menemani belajar dan bekerja.',color:'#9bcdd1',download:'https://example.com/download/audio'},
  {id:'p5',name:'Rekam Video dari Nol',category:'Video',price:65000,description:'Pelajari perencanaan, pengambilan gambar, hingga editing video.',color:'#e7a9a2',download:'https://example.com/download/video'},
  {id:'p6',name:'InvoiceKit',category:'Aplikasi',price:79000,description:'Aplikasi ringkas untuk membuat invoice profesional dengan cepat.',color:'#e5d486',download:'https://example.com/download/invoice'}
];
const rupiah = n => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
let products = JSON.parse(localStorage.getItem('bp_products') || 'null') || initialProducts;
let cart = JSON.parse(localStorage.getItem('bp_cart') || '[]');
let orders = JSON.parse(localStorage.getItem('bp_orders') || '[]');
let selectedCategory = 'Semua'; let selectedWallet = 'DANA';
const REMOTE=window.BANDA_CONFIG?.supabaseUrl&&window.BANDA_CONFIG?.publishableKey?window.BANDA_CONFIG:null;
let adminToken=sessionStorage.getItem('bp_admin_token')||'';
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
const headers=(token='')=>({apikey:REMOTE.publishableKey,authorization:`Bearer ${token||REMOTE.publishableKey}`});
async function remoteProducts(){if(!REMOTE)return;const r=await fetch(`${REMOTE.supabaseUrl}/rest/v1/products?select=*&is_active=eq.true&order=created_at.desc`,{headers:headers()});if(!r.ok)throw new Error('Katalog Supabase tidak dapat dimuat.');const rows=await r.json();products=rows.map(p=>({...p,cover:p.cover_url?`url(${p.cover_url}) center/cover`:null,color:'#d7ef7c'}));cart=cart.filter(id=>products.some(p=>p.id===id));save();renderProducts();renderCart()}
async function uploadToStorage(bucket,file,folder){if(!file?.size)return null;const clean=file.name.replace(/[^a-z0-9._-]/gi,'_');const path=`${folder}/${Date.now()}-${clean}`;const r=await fetch(`${REMOTE.supabaseUrl}/storage/v1/object/${bucket}/${path}`,{method:'POST',headers:{...headers(adminToken),'content-type':file.type||'application/octet-stream','x-upsert':'false'},body:file});if(!r.ok)throw new Error('Upload file gagal. Pastikan peran admin dan policy Storage sudah aktif.');return path}
function save(){localStorage.setItem('bp_products',JSON.stringify(products));localStorage.setItem('bp_cart',JSON.stringify(cart));localStorage.setItem('bp_orders',JSON.stringify(orders))}
function esc(text){const x=document.createElement('span');x.textContent=text;return x.innerHTML}
function cover(p,mini=false){return `<div class="${mini?'mini-cover':'cover'}" style="background:${p.cover||p.color||'#e6dece'}"><span>${esc(p.name.split(' ').slice(0,2).join(' '))}</span>${mini?'':`<small>${esc(p.category)}</small>`}</div>`}
function renderProducts(){const cats=['Semua',...new Set(products.map(p=>p.category))];$('#filters').innerHTML=cats.map(c=>`<button class="${c===selectedCategory?'active':''}" data-filter="${c}">${c}</button>`).join('');const visible=products.filter(p=>selectedCategory==='Semua'||p.category===selectedCategory);$('#product-list').innerHTML=visible.map(p=>`<article class="product">${cover(p)}<div class="product-info"><span class="category">${esc(p.category)}</span><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="product-bottom"><strong class="price">${rupiah(p.price)}</strong><div class="product-actions"><button class="small-btn" data-add="${p.id}">+ Keranjang</button><button class="small-btn buy" data-buy="${p.id}">Beli</button></div></div></div></article>`).join('')||'<p>Produk belum tersedia di kategori ini.</p>';$$('#filters button').forEach(b=>b.onclick=()=>{selectedCategory=b.dataset.filter;renderProducts()});$$('[data-add]').forEach(b=>b.onclick=()=>addCart(b.dataset.add));$$('[data-buy]').forEach(b=>b.onclick=()=>{addCart(b.dataset.buy);openCheckout()})}
function renderCart(){const items=cart.map(id=>products.find(p=>p.id===id)).filter(Boolean);$('#cart-count').textContent=items.length;$('#cart-items').innerHTML=items.length?items.map(p=>`<div class="cart-row"><div><h4>${esc(p.name)}</h4><span>${esc(p.category)} ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¦ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¦ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â· ${rupiah(p.price)}</span></div><button class="remove" data-remove="${p.id}">Hapus</button></div>`).join(''):'<p class="disclaimer">Keranjang Anda masih kosong.</p>';$('#cart-total').textContent=rupiah(items.reduce((t,p)=>t+p.price,0));$$('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(cart.indexOf(b.dataset.remove),1);save();renderCart()})}
function addCart(id){if(!cart.includes(id)){cart.push(id);save();renderCart();toast('Produk ditambahkan ke keranjang.')}else toast('Produk sudah ada di keranjang.')}
function drawer(open){$('#cart-drawer').classList.toggle('open',open);$('.overlay').classList.toggle('open',open)}
function openCheckout(){if(!cart.length)return toast('Pilih produk terlebih dahulu.');drawer(false);const items=cart.map(id=>products.find(p=>p.id===id)).filter(Boolean);$('#checkout-summary').innerHTML=`<div class="cart-row"><div><h4>${items.length} produk dipilih</h4><span>${items.map(p=>esc(p.name)).join(', ')}</span></div><strong>${rupiah(items.reduce((t,p)=>t+p.price,0))}</strong></div>`;$('#checkout-modal').showModal()}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3600)}
async function adminOrder(action,orderId){
 const r=await fetch('/.netlify/functions/admin-order',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${adminToken}`},body:JSON.stringify({action,orderId})});
 const data=await r.json();if(!r.ok)throw new Error(data.error||'Aksi admin gagal.');return data;
}
let activeOrderToken='';
async function checkOrderStatus(){
 if(!activeOrderToken)return;const title=$('#order-status-title'),copy=$('#order-status-copy'),downloads=$('#order-downloads');title.textContent='Memeriksa status pesanan...';copy.textContent='';downloads.innerHTML='';
 try{const r=await fetch(`/.netlify/functions/download?token=${encodeURIComponent(activeOrderToken)}`);if(!r.ok){title.textContent='Pesanan menunggu verifikasi';copy.textContent='Bukti transfer sudah diterima. Silakan buka kembali halaman ini setelah admin mengonfirmasi pembayaran.';return}const data=await r.json();title.textContent='Pembayaran dikonfirmasi';copy.textContent='Produk Anda siap diunduh. Link unduhan berlaku terbatas.';downloads.innerHTML=data.downloads.map((url,i)=>`<a class="button" href="${url}" target="_blank" rel="noopener">Unduh produk ${i+1} <span>ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã¢â‚¬Å“</span></a>`).join('');}catch(e){title.textContent='Status belum dapat diperiksa';copy.textContent=e.message;}
}
function showOrderStatus(token,code=''){
 activeOrderToken=token;sessionStorage.setItem('bp_order_token',token);if(!location.hash.startsWith('#pesanan='))history.replaceState(null,'',`#pesanan=${token}`);$('#order-status-copy').textContent=code?`Pesanan ${code} diterima. Simpan halaman ini untuk mengecek unduhan setelah pembayaran dikonfirmasi.`:'Memeriksa status pesanan...';$('#order-status-modal').showModal();checkOrderStatus();
}
async function remoteOrders(){
 if(!REMOTE||!adminToken)return;
 const r=await fetch('/.netlify/functions/admin-order',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${adminToken}`},body:JSON.stringify({action:'list'})});
 const data=await r.json();if(!r.ok)throw new Error(data.error||'Transaksi Supabase tidak dapat dimuat.');
 orders=(data.orders||[]).map(o=>({id:o.id,buyer:o.buyer_name,wallet:o.wallet,status:o.status,proofPath:o.proof_path,accessToken:o.access_token,date:new Date(o.created_at).toLocaleString('id-ID'),items:(o.order_items||[]).map(i=>i.product_name)}));
 renderAdmin();
}function renderAdmin(){
 $('#visitor-count').textContent=Number(localStorage.getItem('bp_visitors')||1248).toLocaleString('id-ID');
 $('#order-count').textContent=orders.length;$('#product-count').textContent=products.length;
 $('#order-status').textContent=orders.length?`${orders.filter(o=>o.status==='pending').length} menunggu review`:'Belum ada pesanan';
$('#orders-table').innerHTML=orders.length?orders.map(o=>{const state=o.status==='paid'?'Sudah dibayar':o.status==='rejected'?'Ditolak':'Menunggu verifikasi';const actions=o.status==='pending'?`<button class="edit" data-proof="${o.id}">Lihat bukti</button><button class="delete" data-confirm="${o.id}">Konfirmasi</button>`:'';return `<tr><td>${esc(o.buyer)}<br><small>${esc(o.date)}</small></td><td>${o.items.map(item=>esc(products.find(p=>p.id===item)?.name||item)).join(', ')}</td><td>${esc(o.wallet)}</td><td><span class="status">${state}</span>${actions}</td></tr>`}).join(''):'<tr><td colspan="4">Belum ada transaksi yang masuk.</td></tr>';
 $('#admin-products').innerHTML=products.map(p=>`<div class="admin-product">${cover(p,true)}<div><b>${esc(p.name)}</b><span>${esc(p.category)} ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â· ${rupiah(p.price)}</span></div><button class="edit" data-edit="${p.id}">Edit</button><button class="delete" data-delete="${p.id}">Hapus</button></div>`).join('');
 $$('[data-edit]').forEach(b=>b.onclick=()=>openProductForm(products.find(p=>p.id===b.dataset.edit)));
 $$('[data-delete]').forEach(b=>b.onclick=async()=>{const id=b.dataset.delete;if(!confirm(`Hapus ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¦ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ${products.find(p=>p.id===id).name}ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â?`))return;try{if(REMOTE){const r=await fetch(`${REMOTE.supabaseUrl}/rest/v1/products?id=eq.${id}`,{method:'DELETE',headers:headers(adminToken)});if(!r.ok)throw new Error('Produk gagal dihapus.')}products=products.filter(p=>p.id!==id);cart=cart.filter(i=>i!==id);save();renderAdmin();renderProducts();renderCart();toast('Produk dihapus.')}catch(err){toast(err.message)}})
 $$('[data-proof]').forEach(b=>b.onclick=async()=>{try{const data=await adminOrder('proof',b.dataset.proof);window.open(data.url,'_blank','noopener')}catch(err){toast(err.message)}});
 $$('[data-confirm]').forEach(b=>b.onclick=async()=>{if(!confirm('Konfirmasi bahwa pembayaran benar-benar sudah masuk?'))return;try{const data=await adminOrder('confirm',b.dataset.confirm);const link=`${location.origin}${data.downloadPath}`;prompt('Pembayaran dikonfirmasi. Salin link ini dan kirim ke pembeli:',link);await remoteOrders();toast('Pembayaran dikonfirmasi.')}catch(err){toast(err.message)}});
}
function showAdmin(){document.body.style.background='#f4f1ea';$('main#beranda').hidden=true;$('.site-header').hidden=true;$('footer').hidden=true;$('#admin-dashboard').hidden=false;renderAdmin();remoteOrders().catch(err=>toast(err.message));window.scrollTo(0,0)}
function hideAdmin(){document.body.style.background='';$('main#beranda').hidden=false;$('.site-header').hidden=false;$('footer').hidden=false;$('#admin-dashboard').hidden=true;location.hash='beranda'}
function openProductForm(p){const f=$('#product-form');f.reset();$('#product-modal-title').textContent=p?'Edit produk':'Tambah produk';if(p)Object.entries(p).forEach(([k,v])=>f.elements[k]&&(f.elements[k].value=v));$('#product-modal').showModal()}
$('.cart-open').onclick=()=>drawer(true);$('.overlay').onclick=()=>drawer(false);$('.drawer .close').onclick=()=>drawer(false);$('.checkout').onclick=openCheckout;$('.admin-open').onclick=()=>REMOTE?$('#login-modal').showModal():$('#admin-gate').showModal();$$('.modal-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#checkout-modal .wallets').addEventListener('click',e=>{const b=e.target.closest('button');if(b){selectedWallet=b.dataset.wallet;$$('.wallets button').forEach(x=>x.style.outline='');b.style.outline='2px solid #172b24'}});
$('#check-order-status').onclick=()=>checkOrderStatus();
$('#proof-form').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target);try{if(REMOTE){const proof=form.get('proof');const proofBase64=proof?.size?await new Promise((ok,bad)=>{const rd=new FileReader();rd.onload=()=>ok(rd.result);rd.onerror=bad;rd.readAsDataURL(proof)}):null;const r=await fetch('/.netlify/functions/create-order',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({buyerName:form.get('buyer'),wallet:selectedWallet,productIds:cart,proofBase64,proofName:proof?.name})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Pesanan gagal dibuat.');showOrderStatus(data.accessToken,data.orderCode)}else{orders.push({buyer:form.get('buyer'),wallet:selectedWallet,items:[...cart],date:new Date().toLocaleString('id-ID'),proof:form.get('proof').name});save();toast('Bukti diterima. Pesanan menunggu verifikasi pembayaran.')}cart=[];save();renderCart();$('#checkout-modal').close();e.target.reset()}catch(err){toast(err.message)}};
$('#pin-form').onsubmit=e=>{e.preventDefault();const error=$('#admin-gate .form-error');if(REMOTE){$('#admin-gate').close();$('#login-modal').showModal();return}if(e.target.querySelector('input').value==='banda212'){$('#admin-gate').close();$('#login-modal').showModal();error.textContent=''}else error.textContent='PIN tidak sesuai.'};
$('#login-form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),error=$('#login-modal .form-error');try{if(REMOTE){const r=await fetch(`${REMOTE.supabaseUrl}/auth/v1/token?grant_type=password`,{method:'POST',headers:{...headers(),'content-type':'application/json'},body:JSON.stringify({email:fd.get('email'),password:fd.get('password')})});const data=await r.json();if(!r.ok)throw new Error('Email atau password tidak sesuai.');if(data.user?.app_metadata?.role!=='admin')throw new Error('Akun ini bukan admin.');adminToken=data.access_token;sessionStorage.setItem('bp_admin_token',adminToken);$('#login-modal').close();showAdmin();e.target.reset();return}throw new Error('Mode demo memerlukan konfigurasi lama.')}catch(err){error.textContent=err.message}};$('#logout').onclick=()=>{sessionStorage.removeItem('bp_admin_token');adminToken='';hideAdmin()};$('#new-product').onclick=()=>openProductForm();
$('#product-form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),id=fd.get('id'),existing=products.find(p=>p.id===id);try{if(REMOTE){if(!id&&!fd.get('productFile')?.size)throw new Error('Unggah file produk terlebih dahulu.');const filePath=fd.get('productFile')?.size?await uploadToStorage('digital-files',fd.get('productFile'),'produk'):existing.file_path;const coverPath=fd.get('cover')?.size?await uploadToStorage('covers',fd.get('cover'),'covers'):null;const record={name:fd.get('name'),category:fd.get('category'),price:Number(fd.get('price')),description:fd.get('description'),file_path:filePath};if(coverPath)record.cover_url=`${REMOTE.supabaseUrl}/storage/v1/object/public/covers/${coverPath}`;const r=await fetch(`${REMOTE.supabaseUrl}/rest/v1/products${id?`?id=eq.${id}`:''}`,{method:id?'PATCH':'POST',headers:{...headers(adminToken),'content-type':'application/json',prefer:'return=representation'},body:JSON.stringify(record)});if(!r.ok)throw new Error('Produk gagal disimpan. Cek role admin dan policy database.');await remoteProducts()}else throw new Error('Konfigurasi Supabase belum tersedia.');renderAdmin();$('#product-modal').close();toast('Produk berhasil disimpan.')}catch(err){toast(err.message)}};
if(!sessionStorage.getItem('bp_visited')){sessionStorage.setItem('bp_visited','1');localStorage.setItem('bp_visitors',Number(localStorage.getItem('bp_visitors')||1248)+1)}
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
renderProducts();renderCart();remoteProducts().catch(err=>toast(err.message));
if(location.hash.startsWith('#pesanan='))showOrderStatus(decodeURIComponent(location.hash.slice(10)));
